---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-mysql-data
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-es-data
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-es-backup
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


## Cerebro conf
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: edm-cerebro-conf
#spec:
#  storageClassName: faster
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#
## cerebro logs


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-cerebro-logs
spec:
#  storageClassName: faster
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
