---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edm-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elastest-service: edm-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: elastest
        - name: MYSQL_PASSWORD
          value: elastest
        - name: MYSQL_USER
          value: elastest
        image: elastest/edm-mysql:latest
        name: edm-mysql
        command: ['docker-entrypoint.sh', '--ignore-db-dir=lost+found']
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: edm-mysql
      volumes:
      - name: edm-mysql
        persistentVolumeClaim:
          claimName: edm-mysql-data

---
apiVersion: v1
kind: Service
metadata:
  name: edm-mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    elastest-service: edm-mysql
  type: ClusterIP
