---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: edm-mysql-pv
  labels:
    type: local
    service: mysql
spec:
#  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-mysql-data
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      service: mysql


---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: edm-es-pv
  labels:
    type: local
    service: elastic
spec:
#  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/es"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-es-data
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      service: elastic


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-es-backup
spec:
#  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      service: elastic-backup

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: edm-es-backup-pv
  labels:
    type: local
    service: elastic-backup
spec:
#  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/es-backup"

## Cerebro conf
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: edm-cerebro-conf
#spec:
#  storageClassName: faster
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#
## cerebro logs

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: edm-cerebro-pv
  labels:
    type: local
    service: cerebro
spec:
#  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/cerebro"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edm-cerebro-logs
spec:
#  storageClassName: faster
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      service: cerebro
