---
apiVersion: v1
kind: Service
metadata:
  name: ebs-sparkworker
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    elastest-service: ebs-sparkworker

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ebs-sparkworker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elastest-service: ebs-sparkworker
    spec:
      containers:
      - image: elastest/ebs-spark:latest
        command: ["/usr/bin/supervisord","--configuration=/opt/conf/slave.conf"]
        name: ebs-sparkworker
