---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: restapi
  name: restapi
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    elastest-service: restapi
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        elastest-service: restapi
    spec:
      containers:
      - env:
        - name: EBS_PORT
          value: "5000"
        - name: EBS_SPARK_MASTER_URL
          value: http://ebs-sparkmaster:8080/
        image: elastest/ebs:latest
        name: restapi
