apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $i, $port := .Values.service.ports }}
  - port: {{ $port.externalPort }}
    targetPort: {{ $port.internalPort }}
    protocol: {{ $port.protocol }}
    name: {{ $port.name }}
  {{- end }}
  selector:
    app: {{ template "name" . }}
